### ISSUE TITLE
CSV output into a file

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#20]
It would be nice if we added an output mode to save the data into a CSV file.

**Comment by nikomatsakis** [comment]
Once we fix #30, we can add a command line option to write to a file instead of stdout

https://github.com/nikomatsakis/github-metrics/blob/5a3667f890b4668056c1083905e8ca8fd04bf959/src/main.rs#L38-L56

**Comment by sladyn98** [comment]
So we would need to save this into a csv file right : )

**Comment by sladyn98** [comment]
```
Opt::List {
            org,
            google_sheet: gs,
            verbose: _,
```
So we would add another csv to the options list and then write to a csv file, 

```
fn example() -> Result<(), Box<Error>> {
    let mut wtr = Writer::from_path("foo.csv")?;
    wtr.write_record(&["a", "b", "c"])?;
    wtr.write_record(&["x", "y", "z"])?;
    wtr.flush()?;
    Ok(())
}
``` 
Probably use a csv writer ?

**Comment by angelocatalani** [comment]
Yes, I think so, once we merge https://github.com/optopodi/optopodi/pull/37 , we just need to pass the appropriate file writer to the `consume` method of `Print`. What do you think ?

**Comment by sladyn98** [comment]
Yeah I agree, so should we wait for the #37 to get merged in

**Comment by angelocatalani** [comment]
@sladyn98 #37 has been merged!

**Comment by chazkiker2** [comment]
@nikomatsakis closing this issue since it seems no longer relevant
