### ISSUE TITLE
Parallel loading of data

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#21]
Right now, listing the number of PRs from each repo runs one by one and is very slow. We should parallelize the requests across the various repositories.

**Comment by nikomatsakis** [comment]
Doc Jones is working on this

**Comment by doc-jones** [comment]
Is this still desired after all the changes since it was requested?

**Comment by chazkiker2** [comment]
@doc-jones though I’m sure parallelization wouldn't *hurt*, I’m not sure if that pursuit is all together necessary. it's relatively fast for an app that doesn't need to rocket. 

A better priority would be to not load everything from disk, probably. 

@nikomatsakis, thoughts?

**Comment by doc-jones** [comment]
> @doc-jones though I’m sure parallelization wouldn't _hurt_, I’m not sure if that pursuit is all together _necessary_. it's relatively fast for an app that doesn't need to rocket.
> 
> A better priority would be to not load everything from disk, probably.
> 
> @nikomatsakis, thoughts?

@chazkiker2 I'm trying to close this issue.  Maybe you will want to open an issue to address that feature.

**Comment by chazkiker2** [comment]
@doc-jones 100% a separate issue. wasn't intending that to be an "alternative" to this. completely separate. 

but was just sharing my thoughts.

I'm fine w/ this being closed, but up to Niko :)

**Comment by nikomatsakis** [comment]
I'm inclined to close it.
