### ISSUE TITLE
Count folks who participated on PRs

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#23]
It would be nice to through each active PR in the last 30 days and track who interacted on that PR and in what way. We would aggregate those stats across users to get an idea of who has been actively working on PRs on the repo in the last 30 days.

Something like this.

Per username we track:

* [ ] Number of PRs authored
* [ ] Number of times they reviewed (left a GH review) on a PR not authored by them
* [ ] Number of times they either merged a PR or left a "bors r+" or "bors r=" comment
* [ ] Number of times they commented on somebody else's PR

We could do the same for issues.

We can generate this data into a table.

**Comment by chazkiker2** [comment]
how much of this was resolved in #40?

**Comment by nikomatsakis** [comment]
I think this is kind of "fixed", going to close for now, although we will always need refinement. But better to open specific issues.
