### ISSUE TITLE
Refactor the command-line options

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#26]
The command line configuration is currently

```rust
#[derive(Clap, Debug)]
#[clap(setting = AppSettings::ColoredHelp)]
#[clap(name = "gh-metrics")]
enum Opt {
    /// list all repositories in the given organization and the number of
    /// Pull Requests created in the last 30 days
    List {
        /// name of GitHub organization to analyze
        #[clap(short, long)]
        org: String,

        /// Verbose mode (-v, -vv, -vvv, etc.)
        #[clap(short, long, parse(from_occurrences))]
        verbose: u8,

        #[clap(short, long)]
        google_sheet: Option<String>,
    },
}
```

but I think that the various options (e.g., `org`, `verbose`, `google_sheet`) should really be independent of the command in use. I imagine the command being the way we specify the producer, and the other options being the way we specify the consumer (or options that apply to many producers).

So you'd be able to do things like e.g.

```rust
github-metrics list --csv xxx.csv
github-metrics count-contributors --csv xxx.csv
github-metrics count-contributors --google-sheet xxx
```

**Comment by chazkiker2** [comment]
Relevant comment from https://github.com/optopodi/optopodi/pull/29#discussion_r654541151

**Comment by chazkiker2** [comment]
I'm going to start working on this one 😄

**Comment by chazkiker2** [comment]
@nikomatsakis how do we feel about this issue after PR #40  and #35 

given several of your Zulip messages, I think this repo is headed for plenty of change... but wondering if maybe the scope of this issue has maybe been effectively resolved?

That is to say, I'm comfortable closing this issue if you are. (other than the `-p` flag if that has not been fixed... but that too may be out of scope.)

**Comment by nikomatsakis** [comment]
I'm comfortable closing and adding more specific issues as we see fit
