### ISSUE TITLE
change producer/consumer traits to use anyhow::Error

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#28]
Right now they return `Result<(), String>` but `anyhow::Error` would be better.

**Comment by nikomatsakis** [comment]
I did this for `Producer`

**Comment by chazkiker2** [comment]
if #37 doesn't address this before merge, I'll make a quick PR to finalize this issue.

**Comment by angelocatalani** [comment]
solved: https://github.com/optopodi/optopodi/pull/37
