### ISSUE TITLE
print consumer should not hardcode the labels

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#30]
The [print consumer](https://github.com/nikomatsakis/github-metrics/blob/5a3667f890b4668056c1083905e8ca8fd04bf959/src/metrics/print.rs) currently hardcodes that there are two columns:

https://github.com/nikomatsakis/github-metrics/blob/5a3667f890b4668056c1083905e8ca8fd04bf959/src/metrics/print.rs#L14-L17

It should be rewritten to work for any number of columns

**Comment by nikomatsakis** [comment]
I kind of think we should just convert this to generate a CSV file, and it could always be piped into some kind of pretty printer.

**Comment by nikomatsakis** [comment]
Largely fixed in #32, but there is some follow-up work:

- [x] print header for any number of colums
- [x] default the output mode to CSV, so that it can be pretty-printed (and eventually stored in a file)
- [ ] escape `,` in entry content
- [ ] make a  `test producer` that supplies dummy data to test it

**Comment by angelocatalani** [comment]
solved: https://github.com/optopodi/optopodi/pull/37
