### ISSUE TITLE
add context to errors

### ISSUE THREAD

**Issue by nikomatsakis** [optopodi/optopodi#44]
We should change from anyhow to [eyre](https://crates.io/crates/eyre), since it generates prettier reports. We also should add context to our errors. See [this Zulip thread](https://zulip-archive.rust-lang.org/257204projecterrorhandling/02200remedialeducationforNiko.html) for more information.

**Comment by nikomatsakis** [comment]
Update: #51 moved us over to eyre, but we still need to add context. I think the thing to do is to use `wrap_err` to add interesting context. Here is an example from the docs:

```rust
use eyre::{WrapErr, Result};

fn main() -> Result<()> {
    ...
    it.detach().wrap_err("Failed to detach the important thing")?;

    let content = std::fs::read(path)
        .wrap_err_with(|| format!("Failed to read instrs from {}", path))?;
    ...
}
```

Perhaps @yaahc or @foresterre knows, though -- are there any procedural macros that will let you do a "wrap err" automatically on the result coming out from a given function? That might make a nice extension to `fehler`, actually (which we are using). e.g., it'd be really cool if you could do `#[throws(context = "opening file {name}")]` or whatever and have that work (leveraging the move towards nicer format strings that let you reference variables). I'd like it even more if there were some trivial way to capture the arguments without having to name them. I remember @yoshuawuyts working on something like this? 

(Basically I'm thinking of tracing's `instrument`...but for errors...)

**Comment by foresterre** [comment]
I'm not aware of the existence of such a macro. I've always manually added context to results.

**Comment by yaahc** [comment]
Yea, I don't know of a macro like this, I tend to just use tracing-error and #[instrument] with eyre but having a way to easily add an error to the chain of errors sounds like a great idea. I should make a proc macro for this for eyre.
